# Generated by Django 4.0.5 on 2022-10-25 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('albumId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_id', to='base.album')),
            ],
        ),
    ]
