# Generated by Django 4.0.5 on 2022-10-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_photos_albumid'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='photos',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='photos',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
