# Generated by Django 4.0.5 on 2022-10-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_photos_color_photos_height_photos_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='color',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='height',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='width',
        ),
        migrations.AddField(
            model_name='photos',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='photos',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
