# Generated by Django 4.0.5 on 2022-10-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_photos_color_remove_photos_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='image_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photos',
            name='image_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photos',
            name='image_file',
            field=models.ImageField(blank=True, height_field='image_height', upload_to='images', width_field='image_width'),
        ),
    ]
