# Generated by Django 4.0.5 on 2022-10-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_photos_image_height_photos_image_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='dominant_color',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
