# Generated by Django 4.0.5 on 2022-10-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_photos_dominant_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
