# Generated by Django 4.0.5 on 2022-10-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_photos_image_height_alter_photos_image_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image_file',
            field=models.ImageField(blank=True, height_field='image_height', upload_to='images/', width_field='image_width'),
        ),
    ]
