# Generated by Django 4.0.5 on 2022-10-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_photos_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
