# Generated by Django 4.0.5 on 2022-10-27 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_photos_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='albumId',
            new_name='album',
        ),
    ]
