# Generated by Django 4.0.5 on 2022-10-27 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_albumid_photos_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='image_url',
        ),
    ]
