# Generated by Django 4.0.5 on 2022-10-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_photos_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
