# Generated by Django 4.0.5 on 2022-10-28 10:01

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_photos_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image_file',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='image_height', upload_to='images/', width_field='image_width'),
        ),
    ]
